export default {
  primary: 'royalblue',
  textColor: '#666',
  hypelink: 'deepskyblue',
  black: '#000',
  white: '#ffffff',
  gray: '#E0E0E0',
  gray1: '#999',
  gray2: '#EEE',
  cancel: 'gainsboro',
  green: 'mediumseagreen',
  srvTag: 'green',
  reqTag: 'red',
  tomato: 'tomato',
  brown: 'brown',
  button: '#999',
  buttonRed: '#f44336',
  blue: '#1E90FF',
};
